services:
  postgres:
    image: 'postgres:15'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-soundsphere}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
